['def add_box () \t:\n',
 '\tab = 2\n',
 "\tprint('f')\n",
 '\n',
 '\ta = 2\n',
 '\n',
 '\tdef inline():\n',
 '\n',
 '\t\tdef inline2():\n',
 '\t\t\tprint("fff")\t\n',
 '\n',
 '\treturn ab\n',
 '\n',
 '\n',
 'class Net():\n',
 '\n',
 '\tdef fefe():\n',
 '\t\treturn\n',
 '\n',
 '\n',
 'print("")\n',
 '\n',
 '\n',
 'def brahh(fff):\n',
 '\n',
 '\n',
 '  return 0\n',
 '\n',
 '\n',
 'l = [1, 2, 3, 56, 5]\n',
 'l = [el + 1 for el in l]\n',
 'print(l)']